### ISSUE TITLE
Error 126 in F4SE Log when loading Example Project dll

### ISSUE THREAD

**Issue by ghost** [Ryan-rsm-McKenzie/CommonLibF4#3]
Hi, I am 100% sure that I have done something wrong here but I have no clue what do anymore. I managed to build the Example Project into a DLL file in release x64 but F4SE refuses to load it. I don't have much experience with CMake and c++ package managers. I just kept following instructions until I got the project to build really. Address Lib installed at Data/F4SE/Plugins/

[F4SE Log](https://imgur.com/jUc3Lbt)

[CMake](https://imgur.com/tvYSjlA) Pretty sure I did something wrong here too.

Extremely sorry for bothering you with a stupid question and thanks for your time!

**Comment by Ryan-rsm-McKenzie** [comment]
Use [CFF Explorer](https://ntcore.com/?page_id=388) to check your dll's import directory

**Comment by ghost** [comment]
After much testing it seems that ExampleProject.dll loads only when I copy spdlog.dll and fmt.dll in Fallout4 root directory with Fallout4.exe. Why does it fail to load them when I put them next to ExampleProject.dll in Data/F4SE/Plugins/? Or am I supposed to build my project without any dependencies? I am genuinely confused.

![Screenshot (44)](https://user-images.githubusercontent.com/26927823/116390265-277e3580-a81e-11eb-91d7-fee66be7bda0.png)

**Comment by Ryan-rsm-McKenzie** [comment]
Check that `VCPKG_TARGET_TRIPLET` is set to a `static` triplet

**Comment by ghost** [comment]
Thank you for your time. Again, extremely sorry for bothering you. Everything is working now.
