### ISSUE TITLE
LookupFormByID analogue?

### ISSUE THREAD

**Issue by dlinny-lag** [Ryan-rsm-McKenzie/CommonLibF4#4]
What is analogue of [LookupFormByID](https://github.com/ianpatt/f4se/blob/master/f4se/GameForms.h#L37) function  in your framework?

I guess it is [GetFormByID](https://github.com/Ryan-rsm-McKenzie/CommonLibF4/blob/master/CommonLibF4/include/RE/Bethesda/TESForms.h#L674) but I'm not sure. Could you clarify?

**Comment by Ryan-rsm-McKenzie** [comment]
It is `GetFormByID`

**Comment by dlinny-lag** [comment]
Thanks
